alias: Keypad Arm Away
description: "I do not use a code to arm my system. This is a hold the A key for 3 seconds to arm the system"
triggers:
  - type: turned_on
    device_id: "your device id. Your A key should show up as an entity, so manually creating this automation is best."
    entity_id: "the entity id"
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 3
conditions: []
actions:
  - action: alarmo.arm
    metadata: {}
    data:
      mode: away
      entity_id: alarm_control_panel.alarmo
mode: single
