alias: Keypad Arm Night
description: ''
triggers:
  - type: turned_on
    device_id: your device id. Your A key should show up as an entity, so manually creating this automation is best.
    entity_id: entityID
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 0
      seconds: 2

conditions: []
actions:
  - action: alarmo.arm
    metadata: {}
    data:
      mode: night
      entity_id: alarm_control_panel.alarmo
mode: single
